allowBuilds:
  '@parcel/watcher': true
  bufferutil: true
  es5-ext: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - '@salla.sa/*'
overrides:
  '@salla.sa/ui-google-map-render': 'npm:lit@3.3.3'
  '@salla.sa/ui-address-autocomplete-widget': 'npm:lit@3.3.3'
